conf/urls.py
from django.conf.urls import include, url

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from conf.settings.base import MEDIA_ROOT
from socketio import sdjango

sdjango.autodiscover()
admin.autodiscover()

urlpatterns = [
    # User management
    url("^socket\.io", include(sdjango.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^account/', include('system_account.urls', namespace='account')),
    url(r'^api/', include('rest_service.urls', namespace='api')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    url(r'^', include('plataforma.urls', namespace='app')),

    # url(r'^proto/', include('proto.urls', namespace="proto")),
    # url(r'^conceptboard/', include('conceptboard.urls', namespace="conceptboard")),
    # url(r'^sharedocs/', include('sharedocs.urls', namespace="sharedocs")),
    # url(r'^solidify/', include('solidifyapp.urls', namespace="solidifyapp")),
    # url(r'^lucid/', include('lucid.urls', namespace="lucid")),
]  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

"""
if settings.DEBUG:
   # This allows the error pages to be debugged during development, just visit
   # these url in browser to see how these error pages look like.
   urlpatterns += [
       url(r'^400/$', default_views.bad_request),
       url(r'^403/$', default_views.permission_denied),
       url(r'^404/$', default_views.page_not_found),
       url(r'^500/$', default_views.server_error),
   ]
   """

plataforma/urls.py
from django.conf.urls import url

urlpatterns = [
    # Chat management
    url(r'^$', 'plataforma.views.homepage_logged', name="homepage"),
    url(r'^login/$', 'plataforma.views.login_page', name="login"),
    url(r'^login/find/$', 'plataforma.views.find_team', name='find_team'),
    url(r'^logout/$', 'plataforma.views.logout_view', name="logout"),
    url(r'^apps/$', 'plataforma.views.apps', name="apps"),
    url(r'^register/$', 'plataforma.views.register', name="register"),
    url(r'^register/create/$', 'plataforma.views.create', name="register_create"),
    url(r'^register/create/(?P<slug>[0-9a-zA-Z_-]+)/$', 'plataforma.views.invite_user', name="register_create"),
    url(r'^invite/$', 'plataforma.views.invite_user', name='invite_user'),
    url(r'^call/(?P<roomname>[0-9a-zA-Z_-]+)$', 'plataforma.views.call', name='call_user'),
]

system_account/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'system_account.views.home_profile', name='profile_home'),
    url(r'^settings/$', 'system_account.views.setting_account', name='settings'),
    url(r'^logs/$', 'system_account.views.setting_log', name='logs'),
    url(r'^profile/edit/$', 'system_account.views.setting_profile_edit', name='profile_edit'),
    url(r'^profile/(?P<username>[0-9a-zA-Z_-]+)/$', 'system_account.views.setting_profile', name='profile'),
    url(r'^deactivate/(?P<username>[0-9a-zA-Z_-]+)/$', 'system_account.views.deactivate_account', name='deactivate'),
    url(r'^file/$', 'system_account.views.files_profile', name='file'),
    url(r'^file/snippet/$', 'system_account.views.snippet', name='file_snippet'),
    url(r'^file/snippet/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.snippet', name='file_snippet_edit'),
    url(r'^file/post/$', 'system_account.views.post', name='file_post'),
    url(r'^file/post/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.post', name='file_post_edit'),
    url(r'^file/detail/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.file_detail', name='file_detail'),
    url(r'^file/delete/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.delete_file', name='file_delete'),
    url(r'^file/public/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.get_file', name='file_public'),
    url(r'^messages/$', 'system_account.views.get_messages', name='msg'),
    url(r'^team-directory/$', 'system_account.views.get_team_directory', name='team_directory'),
]

templates/site_template/base.html
{% load staticfiles %} {% load dumper %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | Slack</title>
    {% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/slack/rollup-plastic.css' %}"> {% endblock %}
    <link id="favicon" rel="shortcut icon" href="{% static 'images/favicon-32.png' %}" sizes="16x16 32x32 48x48" type="image/png">
    <link rel="icon" href="{% static 'images/app-256.png' %}" sizes="256x256" type="image/png">
    <script>
        var userlogged = '{{ request.user.username }}',
            companyuser = '{{ request.user.user_profile.company.slug }}',
            apiUrl = window.location.protocol + '//' + window.location.host + '/api/',
            hostUrl = window.location.protocol + '//' + window.location.host,
            cdn_url = hostUrl + '/static';
    </script>
</head>

<body class="{% block body_style %}light_theme nav_close{% endblock %}">
    {% block body %} {% block header %}{% endblock %} {% block navbar %}{% endblock %}
    <!--Nav Bar-->
    <div id="{% block id_container %}page{% endblock %}" class="{% block class_container %}{% endblock %}">
        {% block container %}{% endblock %}
    </div>
    <!--Nav Bar-->
    {% block footer %}{% endblock %} {% endblock %} {% block js_libraries %}{% endblock %} {% block js %}{% endblock %}
</body>

</html>

templates/site_template/base_login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Create a Team{% endblock %} | Slack</title>
    {% block styles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/client/index.css' %}">
    {% endblock %}
    <link id="favicon" rel="shortcut icon" href="{% static 'images/favicon-32.png' %}"
          sizes="16x16 32x32 48x48" type="image/png">
    <link rel="icon" href="{% static 'images/app-256.png' %}" sizes="256x256" type="image/png">
</head>
<body class="{% block body_style %}{% endblock %}">
{% block container %}{% endblock %}

<script type="text/javascript" src="{% static 'js/libraries/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/libraries/pass-strong.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/site_template/footer.html
<footer data-qa="footer">
    <section class="links">
        <div class="grid">
            <div class="col span_1_of_4 nav_col">
                <ul>
                    <li class="cat_1">Using Slack</li>
                    <li><a href="#/is" data-qa="product_footer">Product</a></li>
                    <li><a href="#/pricing">Pricing</a></li>
                    <li><a href="#/hc/en-us">Support</a>
                    </li>
                    <li><a href="#/guides">Slack Guides</a></li>
                    <li><a href="#/videoguides">Video Guides</a></li>
                    <li><a href="#/apps">App Directory</a></li>
                    <li><a href="#/api.slack.com/">API</a></li>
                </ul>
            </div>
            <div class="col span_1_of_4 nav_col">
                <ul>
                    <li class="cat_2">Slack
                        <ts-icon class="ts-icon ts_icon_heart"></ts-icon>
                    </li>
                    <li><a href="#/jobs">Jobs</a></li>
                    <li><a href="#/customers">Customers</a></li>
                    <li><a href="#/developers">Developers</a></li>
                    <li><a href="#/events">Events</a></li>
                    <li><a href="#/slackhq.com/">Blog</a></li>
                    <li><a href="#/varietypack">Podcast</a></li>
                    <li><a href="#/slack-shop.myshopify.com/">Slack Shop</a></li>
                </ul>
            </div>
            <div class="col span_1_of_4 nav_col">
                <ul>
                    <li class="cat_3">Legal</li>
                    <li><a href="#/privacy-policy">Privacy</a></li>
                    <li><a href="#/security">Security</a></li>
                    <li><a href="#/terms-of-service">Terms of Service</a></li>
                    <li><a href="#/policies">Policies</a></li>
                </ul>
            </div>
            <div class="col span_1_of_4 nav_col">
                <ul>
                    <li class="cat_4">Handy Links</li>
                    <li><a href="#/downloads">Download desktop app</a></li>
                    <li><a href="#/downloads">Download mobile app</a></li>
                    <li><a href="#/brand-guidelines">Brand Guidelines</a></li>
                    <li><a href="#/slackatwork.com/">Slack at Work</a></li>
                    <li><a href="#/status.slack.com/">Status</a></li>
                </ul>
            </div>
        </div>
    </section>

    <div class="footnote">
        <section>
            <a href="#/slack.com/">
                <ts-icon class="ts-icon ts_icon_slack_pillow" aria-hidden="true"></ts-icon>
            </a>
            <ul>
                <li>
                    <a href="#/help/contact">Contact Us</a>
                </li>
                <li>
                    <a href="#/twitter.com/SlackHQ">
                        <ts-icon class="ts-icon ts_icon_twitter" aria-hidden="true"></ts-icon>
                    </a>
                </li>
                <li class="yt">
                    <a href="#/www.youtube.com/channel/UCY3YECgeBcLCzIrFLP4gblw">
                        <ts-icon class="ts-icon ts_icon_youtube" aria-hidden="true"></ts-icon>
                    </a>
                </li>
            </ul>
        </section>
    </div>
</footer>

templates/site_template/header.html
{% load staticfiles %}
<header class="headroom headroom--top">
    <a id="menu_toggle" class="" data-qa="menu_toggle_hamburger">
        <span class="menu_icon"></span>
        <span class="menu_label">Menu</span>
        <span class="vert_divider"></span>
    </a>
    <h1 id="header_team_name" class="inline_block">
        <a href="{% url 'account:profile_home' %}">
            <i class="ts_icon ts_icon_home"></i>
            {{ request.user.user_profile.company.name }}
        </a>
    </h1>
    <div class="header_nav">
        <div class="header_btns float_right">
            <a id="team_switcher" data-qa="team_switcher">
                <i class="ts_icon ts_icon_th_large ts_icon_inherit"></i>
                <span class="block label">Teams</span>
            </a>
            {% comment %}<a href="#help" id="help_link" data-qa="help_link">
                <i class="ts_icon ts_icon_life_ring ts_icon_inherit"></i>
                <span class="block label">Help</span>
            </a>{% endcomment %}
            <a href="{% url 'app:homepage' %}">
                <img src="{% static 'images/ios-64.png' %}"
                     srcset="{% static 'images/ios-32.png' %} 1x, {% static 'images/ios-64.png' %} 2x">
                <span class="block label">Launch</span>
            </a>
        </div>
        <ul id="header_team_nav">
            <li class="active">
                <a>
                    <i class="ts_icon small ts_icon_check_circle_o active_icon s"></i>
                    <i class="team_icon small default">{{ request.user.user_profile.company.name|make_list|first|upper }}</i>
                    <span class="switcher_label team_name">{{ request.user.user_profile.company.name }}</span>
                </a>
            </li>
            {% comment %}<li id="add_team_option">
                <a href="#signin" target="_top">
                    <i class="ts_icon ts_icon_plus team_icon small"></i>
                    <span class="switcher_label">Sign in to another team...</span>
                </a>
            </li>{% endcomment %}
        </ul>
    </div>
</header>

templates/site_template/navBar.html
{% load staticfiles %}
<nav id="site_nav" class="hidden">
    <div id="site_nav_contents">
        <div id="user_menu">
            <div id="user_menu_contents">
                <div id="user_menu_avatar">
                    <span class="member_image thumb_48"
                          style="background-image:
                                  {% if request.user.profile.image %}
                                      url('{{ request.user.profile.image.url }}'),
                                  {% endif %}
                                  url('{% static 'images/default_avatar.jpg' %}')"></span>
                    <span class="member_image thumb_36"
                          style="background-image:
                                  {% if request.user.profile.image %}
                                      url('{{ request.user.profile.image.url }}'),
                                  {% endif %}
                                  url('{% static 'images/default_avatar.jpg' %}')"></span>
                </div>
                <h3>Signed in as</h3>
                <span id="user_menu_name">{{ request.user.username }}</span>
            </div>
        </div>

        <div class="nav_contents">
            <ul class="primary_nav">
                <li><a href="{% url 'app:homepage' %}" data-qa="app"><i class="ts_icon ts_icon_angle_arrow_up_left"></i>Back to Slack</a></li>
                <li><a href="{% url 'account:profile_home' %}"><i class="ts_icon ts_icon_home"></i>Home</a>
                </li>
                <li><a href="{% url 'account:settings' %}" data-qa="account_profile"><i
                        class="ts_icon ts_icon_user"></i>Account &amp; Profile</a></li>
                {% comment %}<li><a href="#/apps/manage" data-qa="configure_apps" target="_blank"><i
                        class="ts_icon ts_icon_plug"></i>Configure Apps</a></li>{% endcomment %}
                <li><a href="{% url 'account:msg' %}" data-qa="archives"><i
                        class="ts_icon ts_icon_archive"></i>Message Archives</a></li>
                <li><a href="{% url 'account:file' %}"><i
                        class="ts_icon ts_icon_all_files clear_blue"></i>Files</a></li>
                <li><a href="{% url 'account:team_directory' %}" data-qa="team_directory"><i
                        class="ts_icon ts_icon_team_directory"></i>Team Directory</a></li>
                {% comment %}<li><a href="#/stats" data-qa="statistics"><i
                        class="ts_icon ts_icon_dashboard"></i>Statistics</a></li>
                <li><a href="#/customize" data-qa="customize"><i
                        class="ts_icon ts_icon_magic"></i>Customize</a></li>{% endcomment %}
                {% if request.user.profile.type == "owner" %}
                    <li><a href="#/account/team" data-qa="team_settings"><i
                            class="ts_icon ts_icon_cog_o"></i>Team Settings</a></li>
                {% endif %}
            </ul>
        </div>

        <div id="footer">
            <ul id="footer_nav">
                {% comment %}<li><a href="#/is" data-qa="tour">Tour</a></li>
                <li><a href="#/downloads" data-qa="download_apps">Download Apps</a></li>
                <li><a href="#/brand-guidelines" data-qa="brand_guidelines">Brand
                    Guidelines</a></li>
                <li><a href="#/help" data-qa="help">Help</a></li>
                <li><a href="#/api.slack.com" target="_blank" data-qa="api">API<i
                        class="ts_icon ts_icon_external_link small_left_margin ts_icon_inherit"></i></a></li>
                <li><a href="#/pricing" data-qa="pricing">Pricing</a></li>
                <li><a href="#/help/requests/new" data-qa="contact">Contact</a></li>
                <li><a href="#/terms-of-service" data-qa="policies">Policies</a></li>
                <li><a href="#/slackhq.com/" target="_blank" data-qa="our_blog">Our Blog</a></li>{% endcomment %}
                <li><a href="{% url 'app:logout' %}">Sign Out<i
                        class="ts_icon ts_icon_sign_out small_left_margin ts_icon_inherit"></i></a></li>
            </ul>
            {% comment %}<p id="footer_signature">Made with <i class="ts_icon ts_icon_heart"></i> by Slack</p>{% endcomment %}
        </div>
    </div>
</nav>

templates/site_template/template.html
{% extends 'site_template/base.html' %}
{% load staticfiles %}
{% block title %}Welcome{% endblock %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/slack/guides.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slack/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slack/footer.css' %}">
{% endblock %}
{% block js_libraries %}
    <script type="text/javascript" src="{% static 'js/libraries/jquery/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/libraries/bootstrap/bootstrap.js' %}"></script>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/site/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/site/account.js' %}"></script>
{% endblock %}
{% block header %}
    {% include 'site_template/header.html' %}
{% endblock %}
{% block navbar %}
    {% include 'site_template/navBar.html' %}
{% endblock %}
{% block container %}
    <div id="page_contents">
        {% block main_container %}PROFILE{% endblock %}
    </div>
    <div id="overlay"></div>
{% endblock %}