conf/urls.py
from django.conf.urls import include, url

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from conf.settings.base import MEDIA_ROOT
from socketio import sdjango

sdjango.autodiscover()
admin.autodiscover()

urlpatterns = [
    # User management
    url("^socket\.io", include(sdjango.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^account/', include('system_account.urls', namespace='account')),
    url(r'^api/', include('rest_service.urls', namespace='api')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    url(r'^', include('plataforma.urls', namespace='app')),

    # url(r'^proto/', include('proto.urls', namespace="proto")),
    # url(r'^conceptboard/', include('conceptboard.urls', namespace="conceptboard")),
    # url(r'^sharedocs/', include('sharedocs.urls', namespace="sharedocs")),
    # url(r'^solidify/', include('solidifyapp.urls', namespace="solidifyapp")),
    # url(r'^lucid/', include('lucid.urls', namespace="lucid")),
]  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

"""
if settings.DEBUG:
   # This allows the error pages to be debugged during development, just visit
   # these url in browser to see how these error pages look like.
   urlpatterns += [
       url(r'^400/$', default_views.bad_request),
       url(r'^403/$', default_views.permission_denied),
       url(r'^404/$', default_views.page_not_found),
       url(r'^500/$', default_views.server_error),
   ]
   """

plataforma/urls.py
from django.conf.urls import url

urlpatterns = [
    # Chat management
    url(r'^$', 'plataforma.views.homepage_logged', name="homepage"),
    url(r'^login/$', 'plataforma.views.login_page', name="login"),
    url(r'^login/find/$', 'plataforma.views.find_team', name='find_team'),
    url(r'^logout/$', 'plataforma.views.logout_view', name="logout"),
    url(r'^apps/$', 'plataforma.views.apps', name="apps"),
    url(r'^register/$', 'plataforma.views.register', name="register"),
    url(r'^register/create/$', 'plataforma.views.create', name="register_create"),
    url(r'^register/create/(?P<slug>[0-9a-zA-Z_-]+)/$', 'plataforma.views.invite_user', name="register_create"),
    url(r'^invite/$', 'plataforma.views.invite_user', name='invite_user'),
    url(r'^call/(?P<roomname>[0-9a-zA-Z_-]+)$', 'plataforma.views.call', name='call_user'),
]

templates/registro/login.html
{% extends 'site_template/base.html' %}
{% block title %}Login{% endblock %}
{% block container %}
    <div class="span_4_of_6 col float_none margin_auto no_right_padding">
        <p id="error_unknown" class="alert alert_error" style="{% if not message %}display: none;{% endif %}">
            <i class="ts_icon ts_icon_warning"></i> Hmmm... something went wrong. Please try again.</p>
    </div>

    <div class="real_content card align_center span_4_of_6 col float_none margin_auto large_bottom_margin right_padding large_bottom_padding">
        <h1 id="signin_header"> Sign in to <span class="break_word">Slack</span></h1>
        <div class="col span_4_of_6 float_none margin_auto large_bottom_margin">
            <form id="signin_form" method="post" accept-encoding="UTF-8">
                {% csrf_token %}
                <p>Enter your <strong>email address</strong> and <strong>password</strong>.</p>
                <p class=" no_bottom_margin">
                    {{ form.email }}
                </p>
                <p class=" small_bottom_margin">
                    {{ form.password }}
                </p>
                <p>
                    <button id="signin_btn" type="submit" class="btn btn_large full_width ladda-button"
                            data-style="expand-right"><span class="ladda-label">Sign in</span><span
                            class="ladda-spinner"></span></button>
                </p>
                <p>
                    <label class="checkbox">
                        <input type="checkbox" name="remember" checked="">
                        Keep me signed in
                    </label>
                </p>
                <p class="small"><a id="forgot-pw" href="/forgot" class="bold">I forgot my password</a></p>
            </form>
        </div>
        <p class="subtle_silver small"></p>
    </div>
{% endblock %}

templates/registro/register_first.html
{% extends 'site_template/base_login.html' %}
{% load staticfiles %}
{% block body_style %}no_header full_height no_margin full_bleed{% endblock %}
{% block container %}
    <div id="signup_flow" class="full_height fs_split" data-step="email">
        <div id="signup_wrapper" class="fs_split_pane fs_split_pane_left">

            <form class="fs_split_flex_wrapper" method="get" action="{% url 'app:register_create' %}">
                <a class="logo_link" href="{% url 'app:homepage' %}">
                    <img id="slack_logo" src="{% static 'images/slack_logo_240.png' %}" title="Slack" width="120"
                         height="137">
                </a>

                <div id="ratelimit_alert" class="header_error_message hidden bottom_margin">
                    <h3>Whoa, you’re going too fast!</h3>
                    Slow down a bit. You might have better luck if you try again in a minute.
                </div>
                <div id="api_failed_alert" class="header_error_message hidden bottom_margin"></div>


                <div id="email_form_body" class="fs_split_body">
                    <h1>Create a new team</h1>
                    <label id="email_label"><span class="normal">Your </span>email address</label>
                    <input placeholder="you@yourdomain.com" id="signup_email" name="signup_email" spellcheck="false"
                           autocorrect="off" type="text">
                    <p class="error_message"></p>
                </div>

                <div id="submit" class="fs_split_footer">
                    <div class="button_container">
                        <button id="submit_btn" class="btn btn_large ladda-button" disabled="true">
                            <span class="ladda-label">Next
                                <ts-icon class="ts_icon_arrow_right" aria-hidden="true"></ts-icon>
                            </span>
                        </button>
                    </div>
                </div>

                <p id="legalese_mobile" class="show_on_mobile">
                    By proceeding to create your account and use Slack, you are agreeing to our
                    <a class="bold" href="#/slack.com/terms-of-service">Terms
                        of Service</a> and <a href="#/slack.com/privacy-policy" class="bold">Privacy Policy</a>.
                    If you do not agree, you cannot use Slack.
                </p>
            </form>
        </div>

        <div id="signup_graphics_pane" class="fs_split_pane fs_split_pane_right">
            <div class="fs_split_flex_wrapper">
                <div id="signup_graphics_container" class="fs_split_body">
                    <div id="signup_graphics" class="fs_split_graphics"
                         style="background-image: url('{% static 'images/register/step1-illi@2x.png' %}');"></div>
                </div>

                <p id="legalese">
                    By proceeding to create your account and use Slack, you are agreeing to our
                    <a class="bold" href="#/slack.com/terms-of-service">Terms of
                        Service</a> and <a href="#/slack.com/privacy-policy" class="bold">Privacy Policy</a>. If you do
                    not agree, you
                    <nobr>cannot use Slack.</nobr>
                </p>
                <div class="fs_split_footer"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        function isEmail(email) {
            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            return regex.test(email);
        }

        $(document).ready(function () {
            $('#signup_email').bind('select change keyup', function () {
                if (isEmail(this.value))
                    $('#submit_btn').attr('disabled', false);
                else
                    $('#submit_btn').attr('disabled', true);
            });
        });
    </script>
{% endblock %}

templates/registro/register_steps.html
{% extends 'site_template/base_login.html' %}
{% load staticfiles %}
{% block body_style %}no_header full_height no_margin full_bleed{% endblock %}
{% block container %}
    <div id="signup_flow" class="full_height fs_split" data-step="name">
        <div id="signup_wrapper" class="fs_split_pane fs_split_pane_full_width">
            <a class="logo_link" href="{% url 'app:homepage' %}">
                <img id="slack_logo" src="{% static 'images/slack_logo_240.png' %}" title="Slack"></a>

            <form class="fs_split_flex_wrapper" onsubmit="return false;">
                {% csrf_token %}
                <div class="fs_split_body">

                    <div class="create_step_number_label">Step <span id="step"></span> of 5</div>
                    <h1>What’s your name?</h1>
                    <p class="desc">Your name will be displayed along with your messages in Slack.</p>
                    <div class="names no_top_padding bottom_padding" id="name_fields">
                        <label>Your name</label>
                        <div class="col span_1_of_2 no_padding name_field" id="first_name_wrapper">
                            <input placeholder="first name" id="signup_first_name" maxlength="35" autocomplete="off"
                                   required aria-label="First name" type="text">
                            <p class="error_message"></p>
                        </div>
                        <div class="col span_1_of_2 no_padding name_field" id="last_name_wrapper">
                            <input placeholder="last name" id="signup_last_name" maxlength="35" autocomplete="off"
                                   required value="" aria-label="Last name" type="text">
                            <p class="error_message"></p>
                        </div>
                    </div>
                    <div id="username_form_body" class="clear_both">
                        <label id="username_label">Username</label>
                        <div class="input_wrapper username">
                            <p id="username_overlay" class="input_overlay"></p>
                            <input id="signup_username" maxlength="21" autocomplete="off" required
                                   value="{{ username }}" aria-labelledby="username_label username_rule_label"
                                   type="text">
                            <input type="hidden" id="signup_email" value="{{ email }}">
                        </div>
                        <p class="error_message"></p>
                        <p id="username_rule_label" class="subtle_silver">Usernames must be all lowercase, with no
                            spaces. They can only contain letters, numbers, periods, hyphens, and underscores.</p>
                    </div>
                </div>
                <div id="submit" class="fs_split_footer">
                    <div class="button_container">
                        <button id="submit_btn" class="btn btn_large ladda-button">
                            <span class="ladda-label">Continue to Password
                                <ts-icon class="ts_icon_arrow_right" aria-hidden="true"></ts-icon>
                            </span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        var urlSend = "{% url 'app:register_create' %}";
    </script>
    <script type="text/javascript" src="{% static 'js/site/register.js' %}"></script>
{% endblock %}

templates/registro/register_user_invited.html
{% extends 'site_template/base_login.html' %}
{% load staticfiles %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/site/invitation_register.js' %}"></script>
{% endblock %}
{% block body_style %}no_header full_height no_margin full_bleed{% endblock %}
{% block container %}
    <div id="signup_flow" class="full_height fs_split" data-step="name">
        <div id="signup_wrapper" class="fs_split_pane fs_split_pane_full_width">
            <a class="logo_link" href="{% url 'app:homepage' %}">
                <img id="slack_logo" src="{% static 'images/slack_logo_240.png' %}" title="Slack"></a>

            <form class="fs_split_flex_wrapper" method="post">
                {% csrf_token %}
                <div class="fs_split_body">
                    <div class="create_step_number_label">Step <span id="step"></span> of 5</div>
                    <h1>What’s your name?</h1>
                    <p class="desc">Your name will be displayed along with your messages in Slack.</p>
                    <div class="names no_top_padding bottom_padding" id="name_fields">
                        <label>Your name</label>
                        <div class="col span_1_of_2 no_padding name_field" id="first_name_wrapper">
                            <input placeholder="first name" id="signup_first_name" maxlength="35" autocomplete="off"
                                   name="firstName" required aria-label="First name" type="text">
                            <p class="error_message"></p>
                        </div>
                        <div class="col span_1_of_2 no_padding name_field" id="last_name_wrapper">
                            <input placeholder="last name" id="signup_last_name" maxlength="35" autocomplete="off"
                                   name="lastName" required value="" aria-label="Last name" type="text">
                            <p class="error_message"></p>
                        </div>
                    </div>
                    <div id="username_form_body" class="clear_both">
                        <label id="username_label">Username</label>
                        <div class="input_wrapper username">
                            <p id="username_overlay" class="input_overlay"></p>
                            <input id="signup_username" maxlength="21" autocomplete="off" required type="text"
                                   name="username" value="{{ username }}"
                                   aria-labelledby="username_label username_rule_label">
                        </div>
                        <p class="error_message"></p>
                        <p id="username_rule_label" class="subtle_silver">Usernames must be all lowercase, with no
                            spaces. They can only contain letters, numbers, periods, hyphens, and underscores.</p>
                    </div>
                    <div id="username_form_body" class="clear_both">
                        <label class="normal" for="password">Password</label>
                        <input id="signup_password" placeholder="Password" name="password" type="password" required>
                        <div style="position: relative; width: 100%; margin: 5px 0px 1rem;">
                            <div style="height: 4px; background-color: rgb(232, 232, 232); width: 100%; position: absolute; left: 0px;"></div>
                            <div style="height: 4px; width: 0%; position: absolute; left: 0px; background-color: rgb(39, 179, 15);"
                                 id="password-strength-meter"></div>
                            <div style="height: 4px; width: 2px; background-color: rgb(255, 255, 255); position: absolute; left: 25%;"></div>
                            <div style="height: 4px; width: 2px; background-color: rgb(255, 255, 255); position: absolute; left: 50%;"></div>
                            <div style="height: 4px; width: 2px; background-color: rgb(255, 255, 255); position: absolute; left: 75%;"></div>
                        </div>
                        <p class="error_message" id="password_error_message"></p>
                        <p class="subtle_silver">Passwords must be at least 6 characters long, and can’t be things like
                            <i>password</i>, <i>123456</i> or <i>abcdef</i>.</p>
                    </div>
                </div>
                <div id="submit" class="fs_split_footer">
                    <div class="button_container">
                        <button id="submit_btn" class="btn btn_large ladda-button">
                            <span class="ladda-label">Save
                                <ts-icon class="ts_icon_arrow_right" aria-hidden="true"></ts-icon>
                            </span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}