conf/urls.py
from django.conf.urls import include, url

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from conf.settings.base import MEDIA_ROOT
from socketio import sdjango

sdjango.autodiscover()
admin.autodiscover()

urlpatterns = [
    # User management
    url("^socket\.io", include(sdjango.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^account/', include('system_account.urls', namespace='account')),
    url(r'^api/', include('rest_service.urls', namespace='api')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    url(r'^', include('plataforma.urls', namespace='app')),

    # url(r'^proto/', include('proto.urls', namespace="proto")),
    # url(r'^conceptboard/', include('conceptboard.urls', namespace="conceptboard")),
    # url(r'^sharedocs/', include('sharedocs.urls', namespace="sharedocs")),
    # url(r'^solidify/', include('solidifyapp.urls', namespace="solidifyapp")),
    # url(r'^lucid/', include('lucid.urls', namespace="lucid")),
]  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

"""
if settings.DEBUG:
   # This allows the error pages to be debugged during development, just visit
   # these url in browser to see how these error pages look like.
   urlpatterns += [
       url(r'^400/$', default_views.bad_request),
       url(r'^403/$', default_views.permission_denied),
       url(r'^404/$', default_views.page_not_found),
       url(r'^500/$', default_views.server_error),
   ]
   """

plataforma/urls.py
from django.conf.urls import url

urlpatterns = [
    # Chat management
    url(r'^$', 'plataforma.views.homepage_logged', name="homepage"),
    url(r'^login/$', 'plataforma.views.login_page', name="login"),
    url(r'^login/find/$', 'plataforma.views.find_team', name='find_team'),
    url(r'^logout/$', 'plataforma.views.logout_view', name="logout"),
    url(r'^apps/$', 'plataforma.views.apps', name="apps"),
    url(r'^register/$', 'plataforma.views.register', name="register"),
    url(r'^register/create/$', 'plataforma.views.create', name="register_create"),
    url(r'^register/create/(?P<slug>[0-9a-zA-Z_-]+)/$', 'plataforma.views.invite_user', name="register_create"),
    url(r'^invite/$', 'plataforma.views.invite_user', name='invite_user'),
    url(r'^call/(?P<roomname>[0-9a-zA-Z_-]+)$', 'plataforma.views.call', name='call_user'),
]

system_account/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'system_account.views.home_profile', name='profile_home'),
    url(r'^settings/$', 'system_account.views.setting_account', name='settings'),
    url(r'^logs/$', 'system_account.views.setting_log', name='logs'),
    url(r'^profile/edit/$', 'system_account.views.setting_profile_edit', name='profile_edit'),
    url(r'^profile/(?P<username>[0-9a-zA-Z_-]+)/$', 'system_account.views.setting_profile', name='profile'),
    url(r'^deactivate/(?P<username>[0-9a-zA-Z_-]+)/$', 'system_account.views.deactivate_account', name='deactivate'),
    url(r'^file/$', 'system_account.views.files_profile', name='file'),
    url(r'^file/snippet/$', 'system_account.views.snippet', name='file_snippet'),
    url(r'^file/snippet/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.snippet', name='file_snippet_edit'),
    url(r'^file/post/$', 'system_account.views.post', name='file_post'),
    url(r'^file/post/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.post', name='file_post_edit'),
    url(r'^file/detail/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.file_detail', name='file_detail'),
    url(r'^file/delete/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.delete_file', name='file_delete'),
    url(r'^file/public/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.get_file', name='file_public'),
    url(r'^messages/$', 'system_account.views.get_messages', name='msg'),
    url(r'^team-directory/$', 'system_account.views.get_team_directory', name='team_directory'),
]

templates/chat/menu/menu.html
{% load staticfiles %}
<div id="menu" class="menu slack_menu team_menu fade in hidden" style="opacity: 1;">
    <div class="popover_mask"></div>
    <div class="menu_content">
        <div id="menu_header" class="hidden"></div>
        <div id="monkey_scroll_wrapper_for_menu_items_scroller" class="monkey_scroll_wrapper ">
            <div class="monkey_scroll_bar  hidden" {% comment %}style="margin-left: 258px;"{% endcomment %}>
                <div class="monkey_scroll_handle " {% comment %}style="left: -3px;"{% endcomment %}>
                    <div class="monkey_scroll_handle_inner "></div>
                </div>
            </div>
            <div class="monkey_scroll_hider" style="width: 100%;">
                <div id="menu_items_scroller" class="monkey_scroller">
                    <div class="menu_body"></div>
                </div>
            </div>
        </div>
        <div id="menu_footer"></div>
    </div>
</div>

templates/chat/menu/menu_file_options.html
{% load staticfiles %}
<div id="hiddenMenuFile">
    <ul id="menu_items" role="menu_file_option" no-bootstrap="1">
        <li id="copy_file_link" role="menuitem"><a data-url="#URL_LINK#" data-action="copy">Copy link</a></li>
        <li id="comment_file" role="menuitem"><a data-url="#COMMENT#" data-action="comment">Comment</a></li>
        <li id="open_new_window" role="menuitem">
            <a data-url="#NEW_WINDOW_OPEN_FILE#" data-action="open"> Open in new window </a>
        </li>
        <li class="divider"></li>
        {% comment %}<li id="edit_file_space" role="menuitem"><a href="#EDIT_FILE#" target="_blank"> Edit … </a></li>{% endcomment %}
        <div id="element_delete">
            <li class="divider"></li>
            <li id="delete_file" class="danger" role="menuitem">
                <a data-url="#URL_DELETE#" data-action="delete"> Delete file </a>
            </li>
        </div>
    </ul>
</div>

<div id="hiddenMenuFileDetails">
    <ul id="menu_items" role="menu_file_option" no-bootstrap="1">
        <li id="comment_file" role="menuitem"><a data-url="#SHARE#" data-action="share">Share</a></li>
        <li id="copy_file_link" role="menuitem"><a data-url="#URL_LINK#" data-action="copy">Copy link</a></li>
        {% comment %}<li class="divider"></li>
        <li id="edit_file_title" role="menuitem"><a>Rename …</a></li>{% endcomment %}
        <div id="element_delete">
            <li class="divider"></li>
            <li id="delete_file" class="danger" role="menuitem">
                <a data-url="#URL_DELETE#" data-action="delete"> Delete file </a>
            </li>
        </div>
    </ul>
</div>

<div id="hiddenMenuUser">
    <section class="slack_menu_you slack_menu_section" aria-label="you">
        <h2 class="slack_menu_header">
            <a class="member_preview_link member_image thumb_36" target="_blank"
               style="background-image:
                       url({{ MEDIA_URL }}{{ request.user.user_profile.image }}),
                       url({% static 'images/default_avatar.jpg' %})"></a>

            <span class="current_user_name slack_menu_header_primary overflow_ellipsis">{{ request.user.username }}</span>
            <span class="current_name slack_menu_header_secondary overflow_ellipsis">@{{ request.user.username }}</span>
        </h2>
        <ul class="menu_list">
            <li id="member_account_item" data-user="{{ request.user.username }}">
                <a tabindex="0">Profile &amp; account</a>
            </li>
            <li id="member_prefs_item"><a href="{% url 'account:settings' %}" target="_blank">Preferences</a></li>
        </ul>
    </section>
    <section class="slack_menu_current_team slack_menu_section" aria-label="current team">
        <h2 class="slack_menu_header">
            <ts-icon
                    class="team_icon small default">{{ request.user.user_profile.company.name|make_list|first|upper }}</ts-icon>
            <span class="slack_menu_header_primary overflow_ellipsis">{{ request.user.user_profile.company.name }}</span>
        </h2>
        <ul class="menu_list">
            <li id="team_invitations">
                <a>Invite people</a>
            </li>
            <li id="logout" class="logout_url">
                <a href="{% url 'app:logout' %}">Sign out of
                    <strong>{{ request.user.user_profile.company.name }}</strong></a>
            </li>
        </ul>
    </section>
</div>

<div id="hiddenMenuFlexMenu">
    <ul id="menu_items" role="menu" no-bootstrap="1">
        <li id="files_user" class="flexpane_menu_item" data-filetype="user" role="menuitem"><a><i
                class="ts_icon ts_icon_all_files"></i>Your Files</a></li>
        <li id="files_all" class="flexpane_menu_item" data-filetype="all" role="menuitem"><a><i
                class="ts_icon ts_icon_all_files_alt"></i>All Files</a></li>
        <li id="list_team" class="flexpane_menu_item" data-tab-id="team" role="menuitem"><a><i
                class="ts_icon ts_icon_team_directory"></i>Team Directory</a></li>
        {% comment %}<li id="help" class="flexpane_menu_item" role="menuitem"><a><i
                class="ts_icon ts_icon_question_circle"></i>Help<span
                class="badge candy_red_bg hidden help_icon_circle_count">0</span></a></li>
        <li id="whats_new" class="flexpane_menu_item" data-tab-id="whats_new" role="menuitem">
            <a>
                <i class="ts_icon ts_icon_emoji_celebration"></i>What's New
                <span id="whats_new_count" class="badge candy_red_bg hidden"></span>
            </a>
        </li>{% endcomment %}
    </ul>
</div>

<div id="hiddenMenuFileUpload">
    <ul id="menu_items" role="menu" no-bootstrap="1">
        <div class="section_header">
            <hr>
            <span class="header_label menu_mini">New...</span></div>
        <li id="create-snippet" class="file_menu_item">
            <a><i class="file_menu_icon ts_icon ts_icon_create_snippet"></i> Code or text snippet</a>
        </li>
        {% comment %}<li id="gdrive_create_submenu" class="file_menu_item has_submenu">
            <a><i class="file_menu_icon ts_icon ts_icon_google_drive"></i> Google Docs file
                <ts-icon class="ts_icon_caret_right submenu_caret"></ts-icon>
            </a>
        </li>{% endcomment %}
        <li id="create-post" class="file_menu_item">
            <a target="_blank" href="{% url 'account:file_post' %}"><i
                    class="file_menu_icon ts_icon ts_icon_create_post"></i> Post</a>
        </li>
        <div class="section_header">
            <hr>
            <span class="header_label menu_mini">Import a file from...</span></div>
        {% comment %}<li role="menuitem" data-which="gdrive_import">
            <a><i class="file_menu_icon ts_icon ts_icon_google_drive"></i> Google Drive</a>
        </li>{% endcomment %}

        <li id="create-file" class="file_menu_item"><a>
            <i class="file_menu_icon ts_icon ts_icon_laptop"></i> Your computer</a>
        </li>
    </ul>
</div>

templates/chat/menu/menu_list_users.html
<div id="menu" class="menu menu_user_list hidden">
    <div class="popover_mask"></div>
    <div class="menu_content">
        <div id="menu_items_scroller">
            <ul id="menu_items" role="menu_users" no-bootstrap="1"></ul>
        </div>
    </div>
</div>

templates/chat/menu/menu_more_options_header.html
<div id="menu" class="menu flex_menu hidden" style="top: 52.2px; left: 1130px; opacity: 1;">
    <div class="popover_mask"></div>
    <div class="menu_content">
        <div id="menu_header" class="hidden"></div>
        <div id="monkey_scroll_wrapper_for_menu_items_scroller" class="monkey_scroll_wrapper ">
            <div class="monkey_scroll_bar  hidden" style="margin-left: 205.5px;">
                <div class="monkey_scroll_handle " style="left: -3px;">
                    <div class="monkey_scroll_handle_inner "></div>
                </div>
            </div>
            <div class="monkey_scroll_hider" style="width: 100%;">
                <div id="menu_items_scroller" class="monkey_scroller" style="max-height: 569px; width: 218px;">
                    <div class="menu_body"></div>

                    <ul id="menu_items" role="menu" no-bootstrap="1">
                        <li id="files_user" class="flexpane_menu_item" data-filetype="user" role="menuitem"><a><i
                                class="ts_icon ts_icon_all_files"></i>Your Files</a></li>
                        <li id="files_all" class="flexpane_menu_item" data-filetype="all" role="menuitem"><a><i
                                class="ts_icon ts_icon_all_files_alt"></i>All Files</a></li>
                        <li id="list_team" class="flexpane_menu_item" data-tab-id="team" role="menuitem"><a><i
                                class="ts_icon ts_icon_team_directory"></i>Team Directory</a></li>
                        <li id="help" class="flexpane_menu_item" role="menuitem"><a><i
                                class="ts_icon ts_icon_question_circle"></i>Help<span
                                class="badge candy_red_bg hidden help_icon_circle_count">0</span></a></li>
                        <li id="whats_new" class="flexpane_menu_item" data-tab-id="whats_new" role="menuitem">
                            <a>
                                <i class="ts_icon ts_icon_emoji_celebration"></i>What's New
                                <span id="whats_new_count" class="badge candy_red_bg hidden"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="menu_footer"></div>
    </div>
</div>

templates/chat/menu/menu_options_upload_files.html
<div id="menu" class="menu menu_file_create hidden">
    <div class="popover_mask"></div>
    <div class="menu_content">
        <div id="menu_items_scroller">
            <ul id="menu_items" role="menu" no-bootstrap="1">
                <div class="section_header">
                    <hr>
                    <span class="header_label menu_mini">New...</span></div>
                <li data-which="snippet" class="file_menu_item">
                    <a target="_top" href="#/blackmambasoft.slack.com/files/create/snippet">
                        <i class="file_menu_icon ts_icon ts_icon_create_snippet"></i> Code or text snippet</a>
                </li>
                <li id="gdrive_create_submenu" class="file_menu_item has_submenu">
                    <a><i class="file_menu_icon ts_icon ts_icon_google_drive"></i> Google Docs file
                        <ts-icon class="ts_icon_caret_right submenu_caret"></ts-icon>
                    </a>
                </li>
                <li data-which="space" class="file_menu_item">
                    <a target="_top" href="#/blackmambasoft.slack.com/files/create/space">
                        <i class="file_menu_icon ts_icon ts_icon_create_post"></i> Post</a>
                </li>
                <div class="section_header">
                    <hr>
                    <span class="header_label menu_mini">Import a file from...</span></div>
                <li role="menuitem" data-which="gdrive_import">
                    <a><i class="file_menu_icon ts_icon ts_icon_google_drive"></i> Google Drive</a>
                </li>

                <li class="file_menu_item"><a>
                    <i class="file_menu_icon ts_icon ts_icon_laptop"></i> Your computer</a>
                </li>
            </ul>
        </div>
    </div>
</div>