conf/urls.py
from django.conf.urls import include, url

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from conf.settings.base import MEDIA_ROOT
from socketio import sdjango

sdjango.autodiscover()
admin.autodiscover()

urlpatterns = [
    # User management
    url("^socket\.io", include(sdjango.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^account/', include('system_account.urls', namespace='account')),
    url(r'^api/', include('rest_service.urls', namespace='api')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    url(r'^', include('plataforma.urls', namespace='app')),

    # url(r'^proto/', include('proto.urls', namespace="proto")),
    # url(r'^conceptboard/', include('conceptboard.urls', namespace="conceptboard")),
    # url(r'^sharedocs/', include('sharedocs.urls', namespace="sharedocs")),
    # url(r'^solidify/', include('solidifyapp.urls', namespace="solidifyapp")),
    # url(r'^lucid/', include('lucid.urls', namespace="lucid")),
]  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

"""
if settings.DEBUG:
   # This allows the error pages to be debugged during development, just visit
   # these url in browser to see how these error pages look like.
   urlpatterns += [
       url(r'^400/$', default_views.bad_request),
       url(r'^403/$', default_views.permission_denied),
       url(r'^404/$', default_views.page_not_found),
       url(r'^500/$', default_views.server_error),
   ]
   """

system_account/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'system_account.views.home_profile', name='profile_home'),
    url(r'^settings/$', 'system_account.views.setting_account', name='settings'),
    url(r'^logs/$', 'system_account.views.setting_log', name='logs'),
    url(r'^profile/edit/$', 'system_account.views.setting_profile_edit', name='profile_edit'),
    url(r'^profile/(?P<username>[0-9a-zA-Z_-]+)/$', 'system_account.views.setting_profile', name='profile'),
    url(r'^deactivate/(?P<username>[0-9a-zA-Z_-]+)/$', 'system_account.views.deactivate_account', name='deactivate'),
    url(r'^file/$', 'system_account.views.files_profile', name='file'),
    url(r'^file/snippet/$', 'system_account.views.snippet', name='file_snippet'),
    url(r'^file/snippet/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.snippet', name='file_snippet_edit'),
    url(r'^file/post/$', 'system_account.views.post', name='file_post'),
    url(r'^file/post/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.post', name='file_post_edit'),
    url(r'^file/detail/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.file_detail', name='file_detail'),
    url(r'^file/delete/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.delete_file', name='file_delete'),
    url(r'^file/public/(?P<slug>[0-9a-zA-Z_-]+)/$', 'system_account.views.get_file', name='file_public'),
    url(r'^messages/$', 'system_account.views.get_messages', name='msg'),
    url(r'^team-directory/$', 'system_account.views.get_team_directory', name='team_directory'),
]

templates/chat/body.html
{% load staticfiles %}
<div id="client_body">
    <div id="col_messages">
        <div class="row-fluid">
            <div id="col_channels_bg" style="z-index: 0;"></div>
            <div id="col_channels_overlay" class="onboarding_overlay hidden">
                <div class="overlay_mock_text forty_percent_width"></div>
                <div class="overlay_mock_text fifty_percent_width"></div>
                <div class="overlay_mock_text thirty_five_percent_width"></div>
            </div>
            <div id="col_channels" class="channels_list_holder no_unread_msgs_badges default_sort">
                <div id="monkey_scroll_wrapper_for_channels_scroller" class="monkey_scroll_wrapper ">
                    <div class="monkey_scroll_bar  hidden" style="margin-left: 203.5px;">
                        <div class="monkey_scroll_handle " style="left: -3px;">
                            <div class="monkey_scroll_handle_inner "></div>
                        </div>
                    </div>
                    <div class="monkey_scroll_hider " style="width: 199px;">
                        <div id="monkey_scroll_wrapper_for_channels_scroller" class="monkey_scroll_wrapper ">
                            <div class="monkey_scroll_bar  hidden" style="margin-left: 182.5px;">
                                <div class="monkey_scroll_handle " style="left: -3px;">
                                    <div class="monkey_scroll_handle_inner "></div>
                                </div>
                            </div>
                            <div class="monkey_scroll_hider " style="width: 200px;">
                                <div id="channels_scroller" class="show_which_channel_is_active monkey_scroller"
                                     style="height: calc(95vh - 6.6rem); visibility: visible; width: 220px;">
                                    <ul id="all-unreads-list">
                                        <li data-action="show_unread_view"
                                            class="channels_nav_unread show_in_list_even_though_no_unreads unread_link all_unreads hidden">
                                            <a class="overflow_ellipsis channel_name">
                                                <ts-icon class="ts_icon_list"></ts-icon>
                                                All unreads
                                            </a>
                                        </li>
                                    </ul>
                                    <div id="channels" role="navigation" class="section_holder" aria-label="Channels">

                                        <button class="new_channel_btn ts_icon ts_icon_plus_circle channels_list_new_btn btn_unstyle"
                                                data-toggle="tooltip" data-action="create_channel" title=""
                                                aria-label="Create new channel"
                                                data-original-title="Create new channel"></button>
                                        <h2 id="channels_header" class="hoverable">
                                            <button class="channel_list_header_label btn_unstyle"
                                                    data-toggle="tooltip" title=""
                                                    aria-label="Browse all 1 channels"
                                                    data-original-title="Browse all channels">
                                                Channels
                                                <span class="header_count">
                                                    (<span id="channel_header_count">2</span>)
                                                </span>
                                            </button>
                                        </h2>

                                        <ul id="channel-list" aria-label="channels"></ul>
                                        <div class="clear_both"></div>
                                    </div>
                                    <div id="direct_messages" role="navigation" class="section_holder no_bottom_margin"
                                         aria-label="Direct Messages">
                                        <button class="new_dm_btn ts_icon ts_icon_plus_circle channels_list_new_btn btn_unstyle"
                                                data-toggle="tooltip" title="" aria-label="Direct Messages"
                                                data-original-title="Open a Direct Message"></button>

                                        <h2 id="direct_messages_header" class="hoverable" data-toggle="tooltip" title=""
                                            aria-label="Direct Messages" data-original-title="Open a Direct Message">
                                            Direct Messages <span class="header_count hidden">(<span
                                                id="dm_header_count"></span>)</span></h2>
                                        <ul id="im-list">
                                            {% comment %}<li class="member cursor_pointer">
                                                <div class="hotness_icon hidden" id="hotness_D2KQ7LXTR"><span
                                                        class="emoji-outer emoji-sizer"
                                                        style="background: url({% static 'images/sheet_apple_64_indexed_256colors.png' %}) 57.5% 65%;background-size:4100%"></span>
                                                </div>
                                                <a href="#/team/slackbot" class="im_name nuc">
                                                    <span class="unread_highlights hidden">0</span>
                                                    <span class="typing_indicator"></span>
                                                    <span class="overflow_ellipsis">
                                                            <i class="ts_icon ts_icon_heart slackbot_icon"></i>
                                                            slackbot
                                                    </span>
                                                </a>
                                                <button class="ts_icon ts_icon_times_circle im_close btn_unstyle"></button>
                                            </li>{% endcomment %}
                                        </ul>
                                        <div class="clear_both"></div>
                                    </div>

                                    <button id="channel_list_invites_link"
                                            class="channel_list_add_link btn_unstyle dim">
                                        <i class="ts_icon ts_icon_plus_small float_left"></i> Invite people
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="col_channels_footer">
                    <div id="invites_widget"></div>

                    <div id="quick_switcher_btn"><i class="ts_icon ts_icon_filter"></i>
                        <span id="quick_switcher_label"
                              class="quick_switcher_label_windows_alignment">Quick Switcher</span>
                        <span id="quick_switcher_shortcut">Ctrl+K</span></div>
                </div>
            </div>
            {% include 'chat/chat_body.html' %}
        </div>
    </div>
</div>

templates/chat/chat_page.html
{% extends 'site_template/template.html' %}
{% block main_container %}
    hola
{% endblock %}

templates/chat/files_list.html
<div id="monkey_scroll_wrapper_for_file_list_scroller" class="monkey_scroll_wrapper">
    <div id="file_list_by_user" class="list_items" style="overflow-y: auto;height: calc(100vh - 11em);"></div>
</div>

templates/chat/footer.html
<div id="footer">
    <div id="footer_msgs">
{#        {% include 'chat/menu/menu_options_upload_files.html' %}#}
        <div id="messages-input-container" class="offline">
            <a id="primary_file_button" class="file_upload_btn" aria-label="File menu">
                <i class="ts_icon ts_icon_plus_thick"></i>
            </a>
            <form id="message-form">
                <textarea id="message-input" class="with-emoji-menu" autocorrect="off" autocomplete="off"
                          spellcheck="true" placeholder="Message yourself"></textarea>
                <div id="message-input-message"><span></span></div>
                {% comment %}<input id="file-upload" class="offscreen" multiple="multiple" aria-hidden="true"
                       type="file">{% endcomment %}
                {% comment %}<a id="main_emo_menu" class="emo_menu" aria-label="Emoji menu">
                    <i class="ts_icon ts_icon_circle_fill"></i>
                    <i class="ts_icon ts_icon_smile_o"></i>
                    <i class="ts_icon ts_icon_happy_smile"></i>
                </a>{% endcomment %}
            </form>
        </div>
    </div>
    {% comment %}<div id="footer_archives" class="hidden">
        <div id="footer_archives_table">
            <div id="footer_archives_left"><span id="footer_archives_text"></span></div>
            <div id="footer_archives_right"><a class="btn btn_outline btn_small" id="footer_archives_action_button"></a><br><span
                    id="footer_archives_action_tip"></span></div>
        </div>
    </div>{% endcomment %}
</div>

templates/chat/header.html
<header id="client_header">
    {% comment %}<div id="active_channel_name_overlay" class="onboarding_overlay"></div>{% endcomment %}
    <div id="team_menu">
        <button class="notifications_menu_btn ts_icon ts_icon_bell_o ts_tip ts_tip_bottom ts_tip_float btn_unstyle ts_tip_hide"
                aria-label="Notifications Menu">
            <span class="notifications_menu_tip ts_tip_tip">Notifications</span>
        </button>
        <div class="team_name_container top_margin">
            <button class="ts_icon ts_icon_chevron_down team_name_caret btn_unstyle"></button>
            <span id="team_name" class="overflow_ellipsis">{{ request.user.user_profile.company.name }}</span>
        </div>
        <div id="team_menu_overlay" class="onboarding_overlay hidden">
            <div class="overlay_mock_text seventy_percent_width"></div>
        </div>
        <div id="presence_container" class="no_wrap ts_tip ts_tip_bottom ts_tip_left">
            <i id="presence" class="ts_icon ts_icon_presence active" style="opacity: 1;"></i>
            <span class="ts_tip_tip">connecting...</span>
        </div>
        <span id="team_header_user_name" class="current_user_name overflow_ellipsis">{{ request.user.username }}</span>
    </div>
    <div class="channel_header_refactor channel_header">
        <div class="messages_header">
            <div class="channel_title">
                <h2 id="channel_name_container" class="channel_name_container">
                    <span id="channel_name" class="channel_name">
                            <span id="channel_title"></span>
                    </span>
                    <div class="channel_actions_container">
                        <a id="mute_container" class="mute_container ts_tip ts_tip_bottom"></a>
                        {% comment %}<div id="star_container" class="star_container">
                            <button class="star ts_icon ts_icon_star_o ts_icon_inherit star_channel ts_tip ts_tip_top ts_tip_float ts_tip_hidden btn_unstyle">
                                <span class="ts_tip_tip">Star this channel</span>
                            </button>
                        </div>{% endcomment %}
                    </div>
                </h2>

                <!-- channel members -->
                <div id="channel_header_info">
                    <span id="channel_members_toggle_count"
                          class="blue_hover ts_tip ts_tip_bottom ts_tip_leftish"></span>
                    {% comment %}<span class="topic_divider">|</span>
                    <span id="topic_inline_edit" class="channel_topic inline_edit inline_edit_editable">
                    <span class="inline_edit_inner">
                        <span id="channel_topic_text" class="inline_edit_input no_jumbomoji">Company-wide announcements and work-based matters</span>
                    </span>{% endcomment %}
                    </span>
                </div>
            </div>

            <div class="channel_title_info">
                <!-- calls button -->
                <div id="channel_calls_container" class="channel_calls_container">
                    <button class="channel_header_icon channel_calls_button video_call  btn_unstyle ts_tip ts_tip_bottom ts_tip_multiline ts_tip_delay_300 blue_hover hidden">
                        <span class="ts_tip_tip">
                            <span class="ts_tip_multiline_inner">
                                Voice Call.
                            </span>
                        </span>
                        {#                        call_window_offline#}
                        <ts-icon class="call_icon  ts_icon_video_camera"
                                 aria-hidden="true"></ts-icon>
                    </button>
                    <button class="channel_header_icon channel_calls_button voice_call btn_unstyle ts_tip ts_tip_bottom ts_tip_multiline ts_tip_delay_300 blue_hover">
                        <span class="ts_tip_tip">
                            <span class="ts_tip_multiline_inner">
                                Voice Call.
                            </span>
                        </span>
                        <ts-icon class="call_icon  ts_icon_phone" aria-hidden="true"></ts-icon>
                    </button>
                </div>
                {% comment %}<button id="channel_actions_toggle"
                        class="btn_unstyle blue_hover channel_actions_toggle channel_header_icon ts_tip ts_tip_bottom">
                    <span class="ts_tip_tip">Channel Settings</span>
                    <ts-icon class="ts_icon_cog_o" aria-hidden="true"></ts-icon>
                </button>{% endcomment %}
                <button id="details_toggle"
                        class="channel_header_icon btn_unstyle blue_hover channel_details_toggle ts_tip ts_tip_bottom">
                    <span class="ts_tip_tip">Channel Details</span>
                    <ts-icon class="ts_icon_side_panel" aria-hidden="true"></ts-icon>
                </button>
                <div class="divider_bar"></div>
            </div>
        </div>
        <div class="flex_header">
            <div id="search_container">
                <form role="search" id="header_search_form" class="search_form no_bottom_margin">
                    <i class="ts_icon ts_icon_search icon_search"></i>
                    <div class="highlighter_wrapper">
                        <input id="search_terms" class="search_input search_input_highlighted"
                               placeholder="Search" autocomplete="off" maxlength="250" type="text">
                        <div class="highlighter_underlay"><span class="ghost_text">&nbsp;&nbsp;</span></div>
                    </div>
                    <div class="search_clear_icon_wrapper">
                        <button type="button" id="search_clear" class="btn_unstyle search_clear_icon"
                                aria-label="Clear search field">
                            <ts-icon class="ts_icon_times_circle" aria-hidden="true"></ts-icon>
                        </button>
                    </div>
                    <div id="search_autocomplete_popover"
                         class="popover_menu popover_search_menu showing_header hidden">
                        <div class="popover_mask"></div>
                        <span class="arrow"></span>
                        <span class="arrow_shadow"></span>
                        <div id="autocomplete_menu" class="content search_menu">
                            <div data-toggle="datepicker" style="display: none">
                            </div>
                            <div class="monkey_scroll_wrapper">
                                <div class="autocomplete_menu_scrollable monkey_scroller"
                                     style="width: 353px;max-height: 232.8px;overflow-y: auto;">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            {% comment %}<button id="recent_mentions_toggle"
                    class="channel_header_icon btn_unstyle ts_tip ts_tip_bottom ts_tip_rightish">
                <span class="ts_tip_tip not_feature_message_replies_simple">Show Mentions &amp; Reactions</span>
                <ts-icon class="ts_icon_mentions" aria-hidden="true"></ts-icon>
            </button>
            <button id="stars_toggle" class="channel_header_icon btn_unstyle ts_tip ts_tip_bottom ts_tip_rightish">
                <span class="ts_tip_tip">Show Starred Items</span>
                <ts-icon class="ts_icon_star_o" aria-hidden="true"></ts-icon>
            </button>{% endcomment %}
            <button id="flex_menu_toggle"
                    class="channel_header_icon blue_hover btn_unstyle ts_tip ts_tip_bottom ts_tip_right">
                <span class="ts_tip_tip">More Items</span>
                <div id="whats_new_burst" class="all_read"></div>
                <ts-icon class="ts_icon_vertical_ellipsis" aria-hidden="true"></ts-icon>
                <span class="help_icon_icon" id="help_icon_circle_count">0</span>
                <div class="flex_menu_download_circle"></div>
            </button>
            <div id="rxn_toast_div" class="hidden ts_tip ts_tip_bottom"></div>
            <div id="rxn_toast_div" class="hidden ts_tip ts_tip_bottom"></div>
        </div>
    </div>
</header>

templates/chat/menu_right.html
<div id="menu" class="menu flex_menu hidden" style="top: 52.2px; left: 1130px; opacity: 1;">
    <div class="popover_mask"></div>
    <div class="menu_content">
        <div id="menu_header" class="hidden"></div>
        <div id="monkey_scroll_wrapper_for_menu_items_scroller" class="monkey_scroll_wrapper ">
            <div class="monkey_scroll_bar  hidden" style="margin-left: 205.5px;">
                <div class="monkey_scroll_handle " style="left: -3px;">
                    <div class="monkey_scroll_handle_inner "></div>
                </div>
            </div>
            <div class="monkey_scroll_hider" style="width: 100%;">
                <div id="menu_items_scroller" class="monkey_scroller" style="max-height: 569px; width: 218px;">
                    <div class="menu_body"></div>

                    <ul id="menu_items" role="menu" no-bootstrap="1">
                        <li id="files_user" class="flexpane_menu_item" data-filetype="user" role="menuitem"><a><i
                                class="ts_icon ts_icon_all_files"></i>Your Files</a></li>
                        <li id="files_all" class="flexpane_menu_item" data-filetype="all" role="menuitem"><a><i
                                class="ts_icon ts_icon_all_files_alt"></i>All Files</a></li>
                        <li id="list_team" class="flexpane_menu_item" data-tab-id="team" role="menuitem"><a><i
                                class="ts_icon ts_icon_team_directory"></i>Team Directory</a></li>
                        <li id="help" class="flexpane_menu_item" role="menuitem"><a><i
                                class="ts_icon ts_icon_question_circle"></i>Help<span
                                class="badge candy_red_bg hidden help_icon_circle_count">0</span></a></li>
                        <li id="whats_new" class="flexpane_menu_item" data-tab-id="whats_new" role="menuitem">
                            <a>
                                <i class="ts_icon ts_icon_emoji_celebration"></i>What's New
                                <span id="whats_new_count" class="badge candy_red_bg hidden"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="menu_footer"></div>
    </div>
</div>

templates/chat/templates.html
{% extends 'site_template/base.html' %}
{% load staticfiles %}
{% block title %}Chat{% endblock %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/client/rollup-client_core.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/client/rollup-client_primary.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/client/rollup-client_general.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/client/rollup-client_secondary.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/client/incoming_call.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/chosen/chosen.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/codemirror/codemirror.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/codemirror/codemirror_override.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/libraries/jquery/datepicker/datepicker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slack/main.css' %}">
{% endblock %}

{% block body_style %}feature_channel_name_menu light_theme{% endblock %}
{% block id_container %}client-ui{% endblock %}
{% block class_container %}container-fluid sidebar_theme_default {% endblock %}

{% block container %}
    <script>
        var userFileActive = userlogged, localtime = {% now 'U' %},
            sendTo = {type: '', to: ''},
            userImage = '{% if request.user.user_profile.image %}{{ request.user.user_profile.image.url }}{% endif %}',
            userProfile = "{% url 'account:profile' username=request.user.username %}";
    </script>
    {#    {% load socketio_tags %}#}
    {#    {% socketio %}#}
    {% include 'chat/header.html' %}
    {% include 'chat/footer.html' %}
    {% include 'chat/body.html' %}
    {% include 'chat/view_right.html' %}
    {% include 'chat/menu/menu.html' %}
    {% include 'chat/modals.html' %}
{% endblock %}

{% block footer %}
    {% include 'chat/modal/modal.html' %}
{% endblock %}

{% block js_libraries %}
    <script type="text/javascript" src="{% static 'js/libraries/jquery/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/libraries/moment.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/libraries/socket.io.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/libraries/bootstrap/bootstrap-client.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/libraries/jquery/jquery.redirect.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/libraries/jquery/jquery-infinite-scroll.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/chosen/chosen.jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/libraries/idle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/codemirror/codemirror.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/codemirror/codemirror_load.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/codemirror/addon/runmode/myrunmode.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/libraries/jquery/datepicker/datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/libraries/textarea-helper.js' %}"></script>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/site/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/site/file_components.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/site/chat_components.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/site/chat.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/site/chat_file.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/site/chat_client.js' %}"></script>
{% endblock %}